# Public Exporter Configuration
# Author: mmwei3
# Email: mmwei3@iflytek.com
# Date: 2025-04-03

global:
  # Logging configuration
  log_file: "/var/log/public_exporter/exporter.log"
  log_level: "info"  # debug, info, warn, error, fatal, panic
  log_max_age: 7     # days
  log_rotation_time: 24  # hours
  
  # HTTP server configuration
  http_port: 5535
  http_timeout: 30   # seconds
  
  # Default scrape interval for collectors (if not specified)
  default_scrape_interval: 60  # seconds

clusters:
  # Example cluster configuration
  production:
    enabled: true
    collectors:
      # Example Python3 collector
      system_metrics:
        enabled: true
        interval: 30      # seconds
        timeout: 10       # seconds
        script_path: "/scripts/check_system_metrics.py"
        script_type: "python3"
      
      # Example Shell script collector
      network_status:
        enabled: true
        interval: 60      # seconds
        timeout: 15       # seconds
        script_path: "/scripts/check_network.sh"
        script_type: "shell"
      
      # Example Python2 collector (legacy)
      legacy_check:
        enabled: false    # disabled by default
        interval: 120     # seconds
        timeout: 20       # seconds
        script_path: "/scripts/legacy_check.py"
        script_type: "python2"

  # Another cluster example
  staging:
    enabled: true
    collectors:
      app_health:
        enabled: true
        interval: 45      # seconds
        timeout: 25       # seconds
        script_path: "/scripts/check_app_health.py"
        script_type: "python3"
      
      # This collector will use the default interval (60s) from global config
      basic_check:
        enabled: true
        timeout: 5        # seconds
        script_path: "/scripts/basic_check.sh"
        script_type: "shell"

  # Disabled cluster example
  development:
    enabled: false        # This cluster is disabled
    collectors:
      dev_metrics:
        enabled: true
        interval: 30
        timeout: 10
        script_path: "/scripts/dev_metrics.py"
        script_type: "python3"
